### ISSUE TITLE
"Excessive instance identifier sub-OIDs left at MibTableRow" error for a long string

### ISSUE THREAD

**Issue by harelbarash9** [pysnmp/pysnmp#57]
I'm using pysnmplib 5.0.21 tried to snmp walk IP-MIB::ipAddressTable and got the following error:

Traceback (most recent call last):
  File "/usr/src/myapp/adapter_internals/adapter.py", line 94, in collect
    await request.execute(connector)
  File "/usr/src/myapp/adapter_internals/parser.py", line 84, in execute
    return await connector.walk(
  File "/usr/src/myapp/adapter_internals/snmp.py", line 304, in walk
    error_indication, error_status, error_index, response_var_binds = await bulkCmd(
  File "/usr/src/myapp/venv/lib/python3.10/site-packages/pysnmp/hlapi/asyncio/cmdgen.py", line 501, in bulkCmd
    vbProcessor.makeVarBinds(snmpEngine, varBinds), __cbFun,
  File "/usr/src/myapp/venv/lib/python3.10/site-packages/pysnmp/hlapi/varbinds.py", line 39, in makeVarBinds
    __varBinds.append(varBind.resolveWithMib(mibViewController, ignoreErrors=False))
  File "/usr/src/myapp/venv/lib/python3.10/site-packages/pysnmp/smi/rfc1902.py", line 884, in resolveWithMib
    self.__args[1] = ObjectIdentity(self.__args[1]).resolveWithMib(mibViewController)
  File "/usr/src/myapp/venv/lib/python3.10/site-packages/pysnmp/smi/rfc1902.py", line 450, in resolveWithMib
    self.__indices = rowNode.getIndicesFromInstId(suffix)
  File "/usr/src/myapp/venv/lib/python3.10/site-packages/pysnmp/smi/mibs/SNMPv2-SMI.py", line 1256, in getIndicesFromInstId
    raise error.SmiError(
pysnmp.smi.error.SmiError: Excessive instance identifier sub-OIDs left at MibTableRow((1, 3, 6, 1, 2, 1, 4, 32, 1), None): 0.0.3.128

I checked the walk output and see this refers to a long string. Is there any known issue parsing this kind of value?

IP-MIB::ipAddressPrefix.ipv6z."fe80:00:00:00:d4b2:6bff:fe76:a174%3" = 1.3.6.1.2.1.4.32.1.5.732.4.20.254.128.0.0.0.0.0.0.212.178.107.255.254.118.161.116.0.0.0.0.0.0.0.3.128
IP-MIB::ipAddressPrefix.ipv6z."fe80:00:00:00:d4b2:6bff:fe76:a174%4" = 1.3.6.1.2.1.4.32.1.5.314.4.20.254.128.0.0.0.0.0.0.212.178.107.255.254.118.161.116.0.0.0.0.0.0.0.4.128

**Comment by ryanfaircloth** [comment]
Confirmed and fixed in #129.

Not a parsing problem with the long string itself — the failure is that pysnmp treats MIB resolution
of an OBJECT IDENTIFIER *value* as mandatory. `ipAddressPrefix` is a RowPointer into
`ipAddressPrefixTable`, so when the walk fed the response varbinds back in, `ObjectType.resolveWithMib()`
ran full index decoding on the value:

```python
if rfc1902.ObjectIdentifier().isSuperTypeOf(self.__args[1], matchConstraints=False):
    self.__args[1] = ObjectIdentity(self.__args[1]).resolveWithMib(mibViewController)
```

Unconditional, and it ignored `ignoreErrors` entirely — so one undecodable pointer anywhere in the
table aborted the whole `bulkCmd`.

In your data the `InetAddress` length octet says 20 but 24 sub-ids of address material follow, so
`getIndicesFromInstId()` consumed 20 bytes, read `ipAddressPrefixLength` as the next `0`, and reported
`0.0.3.128` left over — which matches your traceback exactly. net-snmp renders it because it never
tries to decode the pointer's index.

Resolving a value is cosmetic; it exists so the value prints as a MIB name, and the bytes are the
peer's choice, not something you addressed. It is now best-effort — on `SmiError` the plain
`ObjectIdentifier` is kept and the walk continues. Your `IP-MIB::ipAddressTable` walk will complete,
with `ipAddressPrefix` values for the affected rows printing in dotted form instead of
`ipAddressPrefixEntry` index notation.

**Comment by ryanfaircloth** [comment]
Fixed in #129, released in 6.0.0-rc.2.
